### ISSUE TITLE
Missing Apache package state?

### ISSUE THREAD

**Issue by jasloe** [geerlingguy/drupal-vm#2030]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.6
VirtualBox 6.0.8r130520
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/jasloe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

### Your OS

 - **macOS** (version)

### Full console output

```
TASK [geerlingguy.apache : Ensure Apache is installed on Debian.] **************
fatal: [local-drupal]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

PLAY RECAP *********************************************************************
local-drupal               : ok=29   changed=2    unreachable=0    failed=1    skipped=30   rescued=0    ignored=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Summary

I'm testing out a few different configurations and running ```vagrant provision``` instead of building the box from the ground up with each config change. 

Does the Apache role need to account for ```installed``` as a valid package state?

**Comment by jasloe** [comment]
Odd...just replicated the issue on a fresh, minimal installation.

**Comment by jasloe** [comment]
Err...think I need to update run ```vagrant box update```. Will report back.

**Comment by geerlingguy** [comment]
@jasloe - One other possibility: you might be running a really old version of Drupal VM—the state was changed to `present` at least a year or two ago.

**Comment by jasloe** [comment]
Yes, it was a combination of factors. Upgrading the box and DVM to 5.2 resolved the issue.

**Comment by jasloe** [comment]
Actually, sorry, have to reopen this. 

My environment is the same as above and now running DVM 5.2. 

Running with ansible 2.8.5 results in:
```
TASK [Check if local known_hosts file is present.] *****************************
fatal: [local-drupal]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: /usr/bin/python3: No such file or directory\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

PLAY RECAP *********************************************************************
local-drupal               : ok=164  changed=0    unreachable=0    failed=1    skipped=376  rescued=0    ignored=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

And running with ansible 2.9.6 still results in:

```
TASK [geerlingguy.apache : Ensure Apache is installed on Debian.] **************
fatal: [local-drupal]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}

PLAY RECAP *********************************************************************
local-drupal               : ok=29   changed=0    unreachable=0    failed=1    skipped=30   rescued=0    ignored=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by jasloe** [comment]
Just tried again from a completely fresh build. Oddly, now I'm getting the python error again:

```
TASK [Check if local known_hosts file is present.] *****************************
fatal: [example]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: /usr/bin/python3: No such file or directory\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}
``` 

I'm assuming the task is looking for python on the virtual machine. 

```$which python``` returns:

```
/usr/bin/python3
```

**Comment by jasloe** [comment]
```force_ansible_local: true``` in my config file seems to work. Only a workaround, I think, and curious what the underlying problem could be.

**Comment by geerlingguy** [comment]
@jasloe - Which base box are you using in your VM? Certain boxes might not have `python3` installed by default, and there were recent changes that switched the default for everything to `python3`.

In which case the http://docs.drupalvm.com/en/latest/configurations/base-os/ docs might need updating.

**Comment by jasloe** [comment]
I'm running: 

```geerlingguy/drupal-vm (virtualbox, 2.0.8)```

**Comment by geerlingguy** [comment]
Strange; it looks like @fsnet also had this issue in #2034. Since your initial problem was resolved according to the issue title, let's move further discussion on this failing task and the `python3` interpreter over to that issue. Thanks!

**Comment by jasloe** [comment]
Uff, feeling not too bright but can't seem to resolve this issue. Still getting 

Still seeing this error on vagrant up and vagrant provision: 

```
TASK [geerlingguy.apache : Ensure Apache is installed on Debian.] **************
fatal: [local-asp-gat]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}
```

I've updated all dependencies:

```
Vagrant 2.2.9
VirtualBox 6.1.8r137981
ansible 2.9.9
  config file = None
  configured module search path = ['/Users/jasloe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

Following the discussion at #2034, my python paths are as follows:

```
host (Python 3.7.7)
➜ which python3
/usr/local/bin/python3
(soft link is /usr/local/bin/python3 -> ../Cellar/python/3.7.7/bin/python3)

guest (Python 3.6.9)
➜ which python3
/usr/bin/python3
```

Understanding from above #2034 that the "path set in ansible_python_interpreter is the same for VM and host", I set a symbolic link on the guest, i.e.:
```
ln -s /usr/bin/python3.6 /usr/local/bin/python3
```
 and changed the ```ansible_python_interpreter``` 
``` key to ```/usr/local/bin/python3``` and reprovisioned.

Not a clue what could be causing the problem.

**Comment by jasloe** [comment]
Worth adding, that I'm attempting to provision using: ```geerlingguy/drupal-vm (virtualbox, 2.0.9)```

**Comment by geerlingguy** [comment]
@jasloe - What version of Drupal VM are you running? If it's too old, the roles included would be out of date and produce those errors.

**Comment by jasloe** [comment]
```
➜  composer show "geerlingguy/drupal-vm"
name     : geerlingguy/drupal-vm
descrip. : A VM for local Drupal development, built with Vagrant + Ansible
keywords : drupal, vagrant, virtual machine, vm
versions : * 5.2.0
type     : vm
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/geerlingguy/drupal-vm.git f8bb9218f068994f731647997c7ace195f6ee193
dist     : [zip] https://api.github.com/repos/geerlingguy/drupal-vm/zipball/f8bb9218f068994f731647997c7ace195f6ee193 f8bb9218f068994f731647997c7ace195f6ee193
path     : /Users/-redacted-/vendor/geerlingguy/drupal-vm
names    : geerlingguy/drupal-vm
```

**Comment by jasloe** [comment]
This is resolved. The python issue was, in fact, a dry hole. I had been reusing my vm/*.config.yml files from project to project and noticed that the offending value was included here:

```
# Other secure defaults.
...
apache_packages_state: installed
...
```

Sorry for all the bother and thanks as always this excellent project.

**Comment by geerlingguy** [comment]
@jasloe - Ah, that'll do it! Glad you could figure it out.
