### ISSUE TITLE
Hanging at Drupal console init

### ISSUE THREAD

**Issue by chrisrikli** [geerlingguy/drupal-vm#909]
First noticed this using a custom config.yml, then cloned and ran an unaltered build.  Same thing.
```
TASK [geerlingguy.drupal-console : Install Drupal Console.] ********************
fatal: [drupalvm]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drupal", "failed": true, "msg": "Request failed", "response": "HTTP Error 500: Internal Server Error", "state": "absent", "status_code": 500, "url": "https://drupalconsole.com/installer"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

RUNNING HANDLER [geerlingguy.mysql : restart mysql] ****************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************
	to retry, use: --limit @/Users/chrisrikli/Vagrant/test/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=133  changed=46   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
OSX: 10.11.6
ansible: 2.0.1.0
vagrant: 1.8.5

**Comment by chrisrikli** [comment]
Closing, I'd not comprehended that the issue was the 500 error from drupalconsole.com

**Comment by chrisrikli** [comment]
Re-opening because while I can load https://drupalconsole.com/installer using wget vagrant is still hanging at this point.  I waited about 20 minutes to make sure it wasn't just something taking a really long time.

**Comment by gettysburger** [comment]
I am having the same issue. Have you had any success getting beyond this?

**Comment by geerlingguy** [comment]
This _could_ be related to some recent changes in one of the Drupal console releases... not sure, since I haven't installed a new release since locking in at (I think) rc5.

Short term/quick-fix is to remove it from installed extras and provision.

**Comment by gettysburger** [comment]
Thanks. That did it. Drupal-VM rocks, BTW.

**Comment by geerlingguy** [comment]
I'm testing locally now, with a fresh VM and just enabling drupalconsole with all the other defaults.

**Comment by geerlingguy** [comment]
See: https://github.com/hechoendrupal/DrupalConsole/issues/2745

It looks like it must be an upstream issue (though it at least installed correctly on a fresh Drupal VM instance for me—I'm running PHP 7 on the Ubuntu 16.04 and/or CentOS 7 box, though—maybe it's because of an older PHP version or base OS?

**Comment by geerlingguy** [comment]
It looks like this was solved upstream (was a Twig issue).

**Comment by simesy** [comment]
Still an issue for me - interested in more information about the source of the issue.

**Comment by jayakrishnanj** [comment]
Still an issue, I removed drupalconsole from config.yml to proceed further.

`TASK [geerlingguy.drupal-console : Ensure Drupal Console is executable.] *******
changed: [dvm]

TASK [geerlingguy.drupal-console : Run Drupal Console init.] *******************

`

**Comment by geerlingguy** [comment]
@jayakrishnanj - What specifically failed? Did it just hang at a certain point? I think it might be best to report issues upstream, as the installation method hasn't changed, but there seem to be frequent install failures due to upstream packaging/hosting...

**Comment by jayakrishnanj** [comment]
@geerlingguy , Whole Drupalvm setup stopped/hanged at the point mentioned above

`TASK [geerlingguy.drupal-console : Ensure Drupal Console is executable.] *******
changed: [dvm]

TASK [geerlingguy.drupal-console : Run Drupal Console init.] *******************`
 for more than 30 min ,when I tried to setup drupalvm , After commenting "drupalconsole" in  config.yml , installation completed successfully.

**Comment by geerlingguy** [comment]
@jayakrishnanj - Does it still happen today? It could still be a Drupal Console issue.

**Comment by zaphoyd** [comment]
We have gotten this error periodically. When inspecting what the 500 error actually is it was them running into some resource limits with their hosting provider. The fix was to either try running at an off-peak time or to remove drupal console from the list of things to install.

Its not really a drupalvm issue but this note might be handy for others who are non the less unable to install drupalvm because of this irritatingly transient error.

**Comment by zaphoyd** [comment]
It looked actually like a github API limit: https://developer.github.com/v3/

For requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour. For unauthenticated requests, the rate limit allows you to make up to 60 requests per hour.

**Comment by geerlingguy** [comment]
Hmm. I wonder if they're not using Basic Authentication/OAuth for the bridge to the GitHub repo? Don't have time to file an issue right now, but might be worth doing.
